name: Github Backup
on:
  schedule: [{cron: "0 0 * * FRI"}]
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: Run script
         run: chmod +x scripts/github-to-s3 && scripts/github-to-s3
         env: 
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
           S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
           S3_KEY: ${{ secrets.S3_KEY }}
           S3_SECRET: ${{ secrets.S3_SECRET }}
           S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
